/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/2024-dev-setup': RouteRecordInfo<'/posts/2024-dev-setup', '/posts/2024-dev-setup', Record<never, never>, Record<never, never>>,
    '/posts/2024-site-refresh-improve-accessibility': RouteRecordInfo<'/posts/2024-site-refresh-improve-accessibility', '/posts/2024-site-refresh-improve-accessibility', Record<never, never>, Record<never, never>>,
    '/posts/change-macos-dock-icon-size': RouteRecordInfo<'/posts/change-macos-dock-icon-size', '/posts/change-macos-dock-icon-size', Record<never, never>, Record<never, never>>,
    '/posts/cloudflare-pages-domain-redirects': RouteRecordInfo<'/posts/cloudflare-pages-domain-redirects', '/posts/cloudflare-pages-domain-redirects', Record<never, never>, Record<never, never>>,
    '/posts/cloudflare-pages-domain-redirects-vi': RouteRecordInfo<'/posts/cloudflare-pages-domain-redirects-vi', '/posts/cloudflare-pages-domain-redirects-vi', Record<never, never>, Record<never, never>>,
    '/posts/cloudflare-pages-surprised-me': RouteRecordInfo<'/posts/cloudflare-pages-surprised-me', '/posts/cloudflare-pages-surprised-me', Record<never, never>, Record<never, never>>,
    '/posts/custom-domains-and-routes-in-cloudflare-workers': RouteRecordInfo<'/posts/custom-domains-and-routes-in-cloudflare-workers', '/posts/custom-domains-and-routes-in-cloudflare-workers', Record<never, never>, Record<never, never>>,
    '/posts/customize-git-bash': RouteRecordInfo<'/posts/customize-git-bash', '/posts/customize-git-bash', Record<never, never>, Record<never, never>>,
    '/posts/default-apps-2023': RouteRecordInfo<'/posts/default-apps-2023', '/posts/default-apps-2023', Record<never, never>, Record<never, never>>,
    '/posts/developer-should-write-blog': RouteRecordInfo<'/posts/developer-should-write-blog', '/posts/developer-should-write-blog', Record<never, never>, Record<never, never>>,
    '/posts/fresh-and-deno': RouteRecordInfo<'/posts/fresh-and-deno', '/posts/fresh-and-deno', Record<never, never>, Record<never, never>>,
    '/posts/from-nextjs-to-astro': RouteRecordInfo<'/posts/from-nextjs-to-astro', '/posts/from-nextjs-to-astro', Record<never, never>, Record<never, never>>,
    '/posts/glitching-logo': RouteRecordInfo<'/posts/glitching-logo', '/posts/glitching-logo', Record<never, never>, Record<never, never>>,
    '/posts/hello-vite': RouteRecordInfo<'/posts/hello-vite', '/posts/hello-vite', Record<never, never>, Record<never, never>>,
    '/posts/i-bought-a-domain': RouteRecordInfo<'/posts/i-bought-a-domain', '/posts/i-bought-a-domain', Record<never, never>, Record<never, never>>,
    '/posts/improve-websites-ux': RouteRecordInfo<'/posts/improve-websites-ux', '/posts/improve-websites-ux', Record<never, never>, Record<never, never>>,
    '/posts/integrate-threads': RouteRecordInfo<'/posts/integrate-threads', '/posts/integrate-threads', Record<never, never>, Record<never, never>>,
    '/posts/is-it-time-to-switch-to-bun': RouteRecordInfo<'/posts/is-it-time-to-switch-to-bun', '/posts/is-it-time-to-switch-to-bun', Record<never, never>, Record<never, never>>,
    '/posts/migrate-from-google-domains-vi': RouteRecordInfo<'/posts/migrate-from-google-domains-vi', '/posts/migrate-from-google-domains-vi', Record<never, never>, Record<never, never>>,
    '/posts/react-refine': RouteRecordInfo<'/posts/react-refine', '/posts/react-refine', Record<never, never>, Record<never, never>>,
    '/posts/revamp-my-site-with-nextjs-tailwindcss': RouteRecordInfo<'/posts/revamp-my-site-with-nextjs-tailwindcss', '/posts/revamp-my-site-with-nextjs-tailwindcss', Record<never, never>, Record<never, never>>,
    '/posts/rose-pine': RouteRecordInfo<'/posts/rose-pine', '/posts/rose-pine', Record<never, never>, Record<never, never>>,
    '/posts/set-up-fish-shell-macos': RouteRecordInfo<'/posts/set-up-fish-shell-macos', '/posts/set-up-fish-shell-macos', Record<never, never>, Record<never, never>>,
    '/posts/set-up-redirect-netlify-vercel': RouteRecordInfo<'/posts/set-up-redirect-netlify-vercel', '/posts/set-up-redirect-netlify-vercel', Record<never, never>, Record<never, never>>,
    '/posts/set-up-redirect-netlify-vercel-vi': RouteRecordInfo<'/posts/set-up-redirect-netlify-vercel-vi', '/posts/set-up-redirect-netlify-vercel-vi', Record<never, never>, Record<never, never>>,
    '/posts/spotify-api-vite-cloudflare-workers': RouteRecordInfo<'/posts/spotify-api-vite-cloudflare-workers', '/posts/spotify-api-vite-cloudflare-workers', Record<never, never>, Record<never, never>>,
    '/posts/spotify-refresh-token': RouteRecordInfo<'/posts/spotify-refresh-token', '/posts/spotify-refresh-token', Record<never, never>, Record<never, never>>,
    '/posts/try-arc-for-windows-without-invite': RouteRecordInfo<'/posts/try-arc-for-windows-without-invite', '/posts/try-arc-for-windows-without-invite', Record<never, never>, Record<never, never>>,
    '/posts/vitesse-vscode-theme': RouteRecordInfo<'/posts/vitesse-vscode-theme', '/posts/vitesse-vscode-theme', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
  }
}
